feat: use custom type for artwork price, wip
artsy/metaphysics pull request #4556
Opened 2022-11-25 16:23 UTC by dariakoko

2022-11-29 10:11 UTC, MounirDhahri requested changes
I think the changes in this file will be breaking old client apps and I believe we should be handling this differently

2022-11-29 11:18 UTC, dblandin reviewed
@MounirDhahri There is some precedent for upgrading fields like this in-place: https://github.com/artsy/metaphysics/pull/969

Any GraphQLInt input should be compatible with a GraphQLFloat input arg type. So this might not cause any problems downstream but we should QA by running Force or Eigen against a locally running copy of Metaphysics or merge and place a deploy block on Metaphysics which QA takes place on staging.

2022-11-29 11:18 UTC, dblandin commented on src/schema/v2/me/myCollectionCreateArtworkMutation.ts
>      pricePaidCents: {
There's a costMinor field further up in this file that is still represented as a GraphQLInt. Should that be updated as well?

2022-11-29 11:18 UTC, dblandin commented on src/schema/v2/fields/money.ts
> +      type: new GraphQLNonNull(GraphQLFloat),
Is this field in the shared Money type used in the My Collection flow?

2022-11-29 13:56 UTC, MounirDhahri commented
@dblandin thanks for the comments. We spoke about this today and Kizito also mentioned that this is possible and he have tested it with @dariakoko.
We spoke also about the fact that this update will be relfected in all money fields in Artsy, and not just MyCollection flow, that's why, what we will do is to use the major and minor fields as ints and this will allow us to accept numbers up to 2 billions which should be more than enough for my collection artworks

2023-04-19 18:57 UTC, mzikherman commented
Bump! (not sure if this is still relevant, if not can be closed)

2023-04-20 04:11 UTC, lordkiz commented
This has been fixed in https://github.com/artsy/metaphysics/pull/4709 and https://github.com/artsy/metaphysics/pull/4702

2023-04-20 04:11 UTC, closed without merging