feat(onyx-637): Add PartnerOfferCreated activity event
artsy/metaphysics pull request #5498
Opened 2024-01-08 17:05 UTC by nickskalkin

description TK

2024-01-08 17:30 UTC, nickskalkin commented on src/schema/v2/notifications/Item/__tests__/index.test.ts
> +          title: "Catty Artwork",
🐈‍⬛

2024-01-08 18:28 UTC, mzikherman requested changes
Looks good overall! Main blocking comment(s) are about the `object_ids` vs `actor_ids` confusion and which one contains the artwork id's.

2024-01-08 18:28 UTC, mzikherman commented on src/schema/v2/notifications/Item/PartnerOfferCreatedNotificationItem.ts
> +        const { artwork_id } = await mePartnerOfferLoader(object_ids[0])
Is this right? I think `object_ids` are the artwork id's already, while offer, which isn't needed to resolve this connection, are the `actor_ids`. So you can use `object_ids` directly and don't need this loader here either.

2024-01-08 18:28 UTC, mzikherman commented on src/schema/v2/notifications/Item/PartnerOfferCreatedNotificationItem.ts
> +      type: GraphQLString,
We have a more structured type for timestamps, that support some common client formatting needs - https://github.com/artsy/metaphysics/blob/98e7b3b7f6dc00932f9614b87f885417d51a4a08/src/lib/date.ts - should likely use that.

2024-01-08 18:28 UTC, mzikherman commented on src/schema/v2/notifications/Item/PartnerOfferCreatedNotificationItem.ts
> +        // object_ids should include a single partner offer id
Same as above, I think `object_ids` and `actor_ids` are getting swapped around here vs. the Gravity PR.

2024-01-08 18:28 UTC, mzikherman commented on src/schema/v2/notifications/index.ts
> +        if (notificationType == "PartnerOfferCreatedActivity") {
As above, I _think_ this isn't needed as `object_ids` should already contain the artwork id's.

2024-01-09 10:25 UTC, nickskalkin commented
@mzikherman sorry for the confusion between actors / objects, I've explained the reason here: https://github.com/artsy/gravity/pull/17224#issuecomment-1882772252

I did 360 and now objects are artworks, which simplifies metaphysics code a bit, could you re-review?

2024-01-09 16:31 UTC, mzikherman approved these changes
Nice!

2024-01-10 13:25 UTC, merged